In [6]:
'''
Update initial.ipynb

1 - Import the dataset
2 - View the dataset (Understand available information | Identify potential issues/errors in the data)
3 - Fix dataset issues (Data cleaning/processing)
4 - Initial analysis (Understand how many customers cancelled)
5 - Detailed analysis (Reasons for customer cancellations; how each column impacts cancellation)

pip install pandas openpyxl nbformat ipykernel plotly

kaggle - training dataset

Note: Useless, empty, or incorrectly formatted information always needs to be addressed during data analysis.

'''

'\nUpdate initial.ipynb\n\n1 - Import the dataset\n2 - View the dataset (Understand available information | Identify potential issues/errors in the data)\n3 - Fix dataset issues (Data cleaning/processing)\n4 - Initial analysis (Understand how many customers cancelled)\n5 - Detailed analysis (Reasons for customer cancellations; how each column impacts cancellation)\n\npip install pandas openpyxl nbformat ipykernel plotly\n\nkaggle - training dataset\n\nNote: Useless, empty, or incorrectly formatted information always needs to be addressed during data analysis.\n\n'

# Import the Dataset

View the dataset

In [12]:
import pandas as pd # "pd" is just a shorthand to save typing.

table = pd.read_csv('cancelamentos.csv')

display(table) # Like print(table), but in a more organized way (only in .ipynb files)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,349936.0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,100634.0,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,301263.0,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,119358.0,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,130955.0,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,195680.0,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,43477.0,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,169273.0,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,310693.0,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,251915.0,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

# Data Processing

Removing (processing) the 'CustomerID' column

In [13]:
# To remove additional columns, use table.drop(columns = ['CustomerID', 'idade',...])
table = table.drop(columns = 'CustomerID')

display(table)

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0


Database column information

In [14]:
display(table.info())

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   50000 non-null  float64
 1   sexo                    49997 non-null  str
 2   tempo_como_cliente      49998 non-null  float64
 3   frequencia_uso          50000 non-null  float64
 4   ligacoes_callcenter     50000 non-null  float64
 5   dias_atraso             50000 non-null  float64
 6   assinatura              50000 non-null  str
 7   duracao_contrato        50000 non-null  str
 8   total_gasto             50000 non-null  float64
 9   meses_ultima_interacao  50000 non-null  float64
 10  cancelou                50000 non-null  float64
dtypes: float64(8), str(3)
memory usage: 4.2 MB

None

Removing empty lines

In [15]:
# table.drop_duplicates() - Removes duplicate values
table = table.dropna()

display(table.info())

<class 'pandas.DataFrame'>
Index: 49996 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   49996 non-null  float64
 1   sexo                    49996 non-null  str
 2   tempo_como_cliente      49996 non-null  float64
 3   frequencia_uso          49996 non-null  float64
 4   ligacoes_callcenter     49996 non-null  float64
 5   dias_atraso             49996 non-null  float64
 6   assinatura              49996 non-null  str
 7   duracao_contrato        49996 non-null  str
 8   total_gasto             49996 non-null  float64
 9   meses_ultima_interacao  49996 non-null  float64
 10  cancelou                49996 non-null  float64
dtypes: float64(8), str(3)
memory usage: 4.6 MB

None

# Initial Analysis

Number of cancellations

In [ ]:
table

Cancellation rate